#ifndef SHOEMANAGERNETWORK_GLOBAL_H
#define SHOEMANAGERNETWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHOEMANAGERNETWORK_LIBRARY)
#  define SHOEMANAGERNETWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHOEMANAGERNETWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOEMANAGERNETWORK_GLOBAL_H
