#ifndef SHOEMANAGERWIDGETS_GLOBAL_H
#define SHOEMANAGERWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHOEMANAGERWIDGETS_LIBRARY)
#  define SHOEMANAGERWIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHOEMANAGERWIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOEMANAGERWIDGETS_GLOBAL_H
