#ifndef SHOEMANAGERMODEL_GLOBAL_H
#define SHOEMANAGERMODEL_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QJsonObject>

#if defined(SHOEMANAGERMODEL_LIBRARY)
#  define SHOEMANAGERMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHOEMANAGERMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOEMANAGERMODEL_GLOBAL_H
